SCREEN_X = 800
SCREEN_Y = 600

MAZE_MARGIN = 50
COLS = 16
ROWS = 12
CELL_SIZE_X = (SCREEN_X - 2 * MAZE_MARGIN) / COLS
CELL_SIZE_Y = (SCREEN_Y - 2 * MAZE_MARGIN) / ROWS

ANIMATION_DELAY = 0.05

FORWARD_COLOR = "red"
BACKTRACKING_COLOR = "gray"
